server:
  port: 8094
#  port: 80
  hostname: localhost
#  hostname: 192.168.0.106
  
spring:
  application:
    name: micro-account
  data:
    mongodb:
      database: db_account
#      uri: mongodb://${server.hostname}:12500/${spring.data.mongodb.database}
      uri: mongodb://arodriguezcu:WoZiG7Enr4sZXJsPA6J1yAICIAeGAzczurFJNm8k3q0apmZjMRPlAdHKqoA4vCnXvwLT40VxnskXjU6AwznsuA==@arodriguezcu.mongo.cosmos.azure.com:10255/${spring.data.mongodb.database}?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@arodriguezcu@
  kafka:
    bootstrap-servers: ${kafka.server.hostname}:${kafka.server.port}
      
kafka:
  server:
    hostname: 20.94.188.219
    port: 9092
    
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: az-eureka-server.azurewebsites.net
            
msg:
  error:
    registro:
      notfound:
        all: CUENTAS NO IDENTIFICADAS
        account: CUENTA NO IDENTIFICADA
        create: CUENTA NO SE PUDO CREAR
        update: CUENTA NO IDENTIFICADA PARA ACTUALIZAR
        delete: CUENTA NO IDENTIFICADA PARA ELIMINAR
      if.exists: CUENTA YA EXISTE
      card.notexists: NUMERO DE TARJETA NO EXISTE
      account.delete: CUENTA ELIMINADA

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 2s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
    instances:
      accountServiceCircuitBreaker:
        baseConfig: default
